content/en/_index.html
Remove what is also a paragraph from the about page, and instead
provide a short blurb about how Lotus functions to support the commons.
=> Update frontpage copy

content/en/_index.html
This has the video we talked about added.
=> embedded give Lotus video on home page

content/en/docs/specs/lotus/addresses.md
Update spec to include the type byte and the change to how the weak
hash was calculated.
=> Update address specification for finalized version of XAddresses

content/en/software/index.html
=> Add links to the Lotus 1.0.0 node binaries

content/en/_index.html, content/en/about/_index.html, content/en/projects/_index.html, content/en/software/index.html, layouts/shortcodes/blocks/section.html
Added a width prop to the section shortcode and implemented it on text blocks to make them more readable
=> Add section width modifier

content/en/docs/guides/mining.md
Version is 1.0.1, but newest is 1.0.2, causing trouble with addresses.
=> Update Lotus QT for Windows in mining.md

nginx.conf
=> Change caching parameters for nginx to avoid needed hard-refreshes

app/components/Header/DropDown.vue, app/components/Header/Header.vue, app/components/Header/MobileMenu.vue, app/components/Header/dropdown.scss, app/pages/credits.vue, app/pages/wallets.vue, app/static/lang/de-DE.js, app/static/lang/en-US.js, app/static/lang/hi-HI.js, app/static/lang/pl-PL.js, app/static/lang/zh-CN.js, docs/content/en/guides/mining.md
=> Add credits page

app/components/Title/Title.vue, app/pages/index.vue, app/static/lang/en-US.js
Inject convertkit widget (per Austin) into the main page so that
people can sign up for a mailing list.
=> Add block to subscribe to mailing list

app/pages/wallets.vue, app/static/lang/de-DE.js, app/static/lang/en-US.js, app/static/lang/hi-HI.js, app/static/lang/pl-PL.js, app/static/lang/zh-CN.js, docs/content/en/guides/mining.md
=> Update node version links to latest v3.3.3

app/components/Header/Header.vue, app/components/Header/MobileMenu.vue
Mags setup a nice free ghost blog that can accept donatins and gather emails/lotus addresses. Link to there instead of thepassage
=> Update blog link to point to the new ghost site

app/pages/credits.vue
Add more people to the credits page, and update the styling to be more pleasing.
=> Update credits and styling thereof

app/pages/wallets.vue, app/static/lang/en-US.js
Use vuetify table instead of manual list for a better appearance, simplify the links so they're more clear when the same wallet supports multiple platforms, and add some additional wallets.
=> Update wallets page to be more asthetic

app/components/Header/menu.ts
=> Fix link to projects

app/components/Banner/Banner.vue, app/components/Banner/banner-style.scss, app/components/Banner/index.js, app/components/Projects/Projects.vue, app/components/Projects/projects.scss, app/pages/index.vue, app/static/lang/en-US.js
Update the first thing people see to be a more compelling "why" for Lotus. Also, remove some things which really shouldn't be on there, or don't make sense now.
=> Update main page to be more compelling

app/pages/credits.vue
=> Add Austin and Alex to contributors

app/components/Banner/Banner.vue, app/components/Banner/banner-style.scss, app/pages/index.vue
Don't want people signing up in two places.
=> Remove signup form as we have moved our blog/newsletter to ghost

app/components/Header/Header.vue, app/components/Header/Settings.vue
=> Make all icons white on scroll down.

app/components/Banner/Banner.vue, app/pages/index.vue, app/static/lang/de-DE.js, app/static/lang/en-US.js, app/static/lang/hi-HI.js, app/static/lang/pl-PL.js, app/static/lang/vi-VI.js, app/static/lang/zh-CN.js
=> Remove empty localization string

app/components/Banner/Banner.vue, app/components/Story/Story.vue, app/static/lang/en-US.js, app/static/lang/pl-PL.js, app/static/lang/vi-VI.js
Clean up main page, and remove the form that nobody was using.
=> [main] Remove animated gifs from main page
